### ISSUE TITLE
Aitchison distance

### ISSUE THREAD

**Issue by Vincev454** [aplantin/pldist#2]
Dear Anna,

Would it be possible to use "pldist" with the Aitchison distance?

Many thanks,
Vince

**Comment by aplantin** [comment]
Hi Vince, 

Yes, you can. The Aitchison distance is the Euclidean distance applied to CLR-transformed data. The two major ways you could imagine using pldist with Aitchison distances are: 

1) Apply the CLR transformation at the sample level (i.e., at each time point for each subject). Then apply the pldist transformation (average change in CLR-transformed abundance per taxon per unit time), and then compute Euclidean distances. 

2) Apply the pldist transformation to proportions (average change in taxon relative abundance per unit time). Then apply the CLR transformation to these relative abundance changes, and then compute Euclidean distances. 

For (1), you would run the data_prep() and pltransform() functions as shown in the vignette, and then calculate Euclidean distances on the dat.quant.clr object within the pltransform() output. 

For (2), you would run the data_prep and pltransform() functions as shown in the vignette, then apply the clr transformation to the dat.quant.prop object within the pltransform() output. Then you could calculate Euclidean distances on that object. 

Best, 
Anna
